Repository vktrbr/optimization_ml, pull requests merged in 2022-03, with the labels that each got.

#4 Type refactoring
  one-dim optim/gold_section_search.py
Labels: refactoring from friends

#36 add x_k in history, change function params type
  MultiDimensionalOptimization/algorithms/gradient_descent_constant_step.py
  MultiDimensionalOptimization/algorithms/gradient_descent_frac_step.py
Labels: bug, algrorithm

#49 35 multidimensional visualization
  .gitatributes
  MultiDimensionalOptimization/drawing/data_converter.py
  MultiDimensionalOptimization/drawing/visualizer.py
  MultiDimensionalOptimization/example_notebook.ipynb
Labels: visualization
